name: Banking

on:
  push:
      branches: 
      - Master
      
jobs:

  BuildProject:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: build banking
          shell: bash
          run: |
            cd banking
            cmake -H. -B_build
            cmake --build _build
          
  Testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: update
        run:  |
          git submodule update --init
          sudo apt install lcov
          sudo apt install g++
      
      - name: test
        shell: bash
        run: |
          cmake -H. -B_build
          cmake --build _build
          cd _build
          ./RunTest
          lcov -t "RunTest" -o lcov.info -c -d .
          
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel: true
          path-to-lcov: ./_built/lcov.info
          coveralls-endpoint: https://coveralls.io

      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
