name: Banking

on:
  push:
      branches: 
      - Master
      
jobs:

  BuildProject:
  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        shell: bash
        run: |
          cmake -H. -B_build
          cmake --build _build
          
  Testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        shell: bash
        run: |
          cd _build
          ./RunTest
        
